services:
  localstack:
    image: localstack/localstack:4.11.1
    environment:
      - LOCALSTACK_HOST=127.0.0.1
      - SERVICES=s3,sqs,sns,dynamodb
      - LS_LOG=WARN
    env_file:
      - ./docker/config/defaults.env
    volumes:
      - ./docker/scripts/localstack:/etc/localstack/init/ready.d
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/READY"]
      interval: 5s
      start_period: 5s
      retries: 3

  mongodb:
    image: mongo:6.0.13
    volumes:
      - ./docker/scripts/mongodb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.hello().ok"]
      interval: 5s
      start_period: 5s
      retries: 3

  trade-imports-gmr-finder:
    image: defradigital/trade-imports-gmr-finder:${TRADE_IMPORTS_GMR_FINDER:-latest}
    env_file:
      - ./docker/config/defaults.env
      - ./docker/config/trade-imports-gmr-finder.env
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/health"]
      interval: 3s
      start_period: 2s
      retries: 3
    ports:
      - "3000:8080"

  trade-imports-gmr-processor:
    image: defradigital/trade-imports-gmr-processor:${TRADE_IMPORTS_GMR_PROCESSOR:-latest}
    env_file:
      - ./docker/config/defaults.env
      - ./docker/config/trade-imports-gmr-processor.env
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/health"]
      interval: 3s
      start_period: 2s
      retries: 3
    ports:
      - "3001:8080"
