name: Run Journey Tests on GitHub

permissions:
  checks: write
  pull-requests: write

on:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    name: Run journey tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Run the tests
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            10.0
        env:
          GVMS_API_CLIENT_ID: ${{ secrets.GVMS_API_CLIENT_ID }}
          GVMS_API_CLIENT_SECRET: ${{ secrets.GVMS_API_CLIENT_SECRET }}
      - run: dotnet restore
      - run: dotnet test
